# spring.mvc.servlet.load-on-startup=1
server:
  port: 3001
spring:
  data:
    mongodb:
      host: mongodb+srv://db-mongodb-haries-app-c430bfeb.mongo.ondigitalocean.com
      database: admin
      username: ayeon
      password: I1Z2E8Ol7N9J6V05
